### ISSUE TITLE
Mix test fails on a newly cloned repo

### ISSUE THREAD

**Issue by crova** [seb3s/kandesk#4]
Hello Sébastien, ça va?

First of all, thanks for this nice little neat tool, looks really useful and clean.

I realized that if we run `mix test` for a newly cloned repo, we'll get a compilation error:
```
** (Cldr.UnknownBackendError) The backend KandeskWeb.Cldr is not known or not a backend module.
    lib/cldr/plug/plug_set_locale.ex:480: Cldr.Plug.SetLocale.validate_cldr/2
    lib/cldr/plug/plug_set_locale.ex:175: Cldr.Plug.SetLocale.init/1
    (plug 1.11.0) lib/plug/builder.ex:304: Plug.Builder.init_module_plug/4
    (plug 1.11.0) lib/plug/builder.ex:288: anonymous fn/5 in Plug.Builder.compile/3
    (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plug 1.11.0) lib/plug/builder.ex:286: Plug.Builder.compile/3
    lib/kandesk_web/router.ex:8: (module)
```

Poking around, I found [this discussion](https://github.com/elixir-cldr/cldr/issues/135) allowing us to fix the issue, there are 2 options to this:
1. add `require KandeskWeb.Cldr` on the top of `router.ex`.
2. bump `ex_cldr` from version `14.0` to `14.1.1` which fixes this compiling issue without needing to change your code.

Given the options, which solution would you say is the better one for the application?
Would you like a pull request to one of them?

Have a good one,
crova

**Comment by seb3s** [comment]
Hello crova,
I tried upgrading to the latest but still get an error. I've commented on the link you provided and I'm waiting from some feedback from the author.

Thanks,
Sébastien

**Comment by kipcole9** [comment]
Sorry for the inconvenience.  Sometimes Elixir can't detect when an atom is a module that needs to be compiled, and this is one of those cases.  Therefore we need to force compilation order and make sure the CLDR backend module is compiled before the router module is compiled.  To do that, simply add `require KandeskWeb.Cldr` to the top of `router.ex`. For example:

```elixir
require KandeskWeb.Cldr

defmodule KandeskWeb.Router do
  use KandeskWeb, :router
  use Pow.Phoenix.Router
.....
```

it appears to compile cleaning on my dev machine (I can't run the tests without setting up the DB which I will try later my day).

Let me know if that resolves the issue?  I will keep looking for ways to avoid this step and will update the documentation to reflect the workaround.

**Comment by seb3s** [comment]
Hello,
yep it fixes it, but reading from the other thread, I thought it has been corrected by the updates you made.
I added "require KandeskWeb.Cldr" for the moment.

Thanks for your feedback

**Comment by seb3s** [comment]
Hello @crova 
I've pushed Option 1 for now that should fix it.
Thanks again
