### ISSUE TITLE
Pb with postgre at install

### ISSUE THREAD

**Issue by hedjour** [seb3s/kandesk#5]
I try to install your software I follow your tuto i get an error than role "kandesk" does not exist.
How can I fixed It ?
Thanks

**Comment by seb3s** [comment]
Hello,
yes you have to create it with psql or your db admin application (I use pgadmin myself).
You can use the "db_create_role.sql" script located in /priv/repo/sql where you replace 'md5encryptedpassword' with your md5 hashed password. 

Then you need to adjust the password in /config/dev.exs with the one you use.
```
config :kandesk, Kandesk.Repo,
  username: "kandesk",
  password: "kandesklocaldev",   <== change it here
```
Hope this helps

**Comment by hedjour** [comment]
Yes It works many thanks I will purpose you a pull request to improve the doc
