### ISSUE TITLE
Moving modal resets form

### ISSUE THREAD

**Issue by crockwave** [seb3s/kandesk#8]
After editing modal form and moving modal, the form values reset.

By adding `phx-update="ignore"` to the div surrounding each form element, the problem goes away

**Comment by seb3s** [comment]
Hello,
This is now fixed with 6d940efcd1023b4667904b5a7a3a517be013702c in a much better way.
I was waiting for the release of liveview 0.17.6 to clean it.
Cheers,
Sébastien.
